---
title: |
       | POLI SCI 395
       | Political Research Seminar
       | Evidence-Informed Decision-Making
       | Spring 2025
format: 
  typst:
    margin:
      x: 1in
      y: 1in
fontsize: 12pt
---

```{=typst} 
#show link: set text(blue)
```

<!-- Remember double space for line skip -->
**Instructor:** Gustavo Diaz (he/him/his)  
**Email:** <gustavo.diaz@northwestern.edu>  
**Lecture:**  Tues/Thurs 2:00 – 3:20pm, Scott Hall 201 Ripton Room  
**Canvas:** TBD  
**Student Hours:** Wednesday 2:00 -- 4:00pm, Scott Hall 103 or [by appointment](https://calendly.com/gustavo-diaz-nu/meetings)

# Course Overview

This seminar explores how evidence generated from statistical research methods can be used to inform decision-making in academia, government, and industry. We will examine the merits and pitfalls of contemporary tools in experimentation and data science when it comes to evaluating policy or justifying organizational change. We will learn that connecting evidence to decisions often requires additional language and argumentation, which will lead us to more advanced techniques designed specifically to inform decision-making with minimal assumptions.

# Content

```{=typst}
#set align(center)
```


| **Week** | **Dates** | **Topic** |
|--: | :----- | :------------- |
| 1 | Thursday, April 3 | [Preliminaries](#w1) |
| 2 | April 8/10 | [The Evidence-Informed Movement](#w2)
| 3 | April 15/17 | [Randomized Controlled Trials](#w3)
| 4 | April 22/24 | [Learning from Experiments](#w4)
| 5 | April 29/May 1 | [Advanced Experimental Designs](#w5)
| 6 | May 6/8 | [Data Science to Help](#w6)
| 7 | May 13/15 | [Data Science to Harm](#w7)
| 8 | May 20/22 | [AI and Experiments](#w8)
| 9 | May 27/29 | [Large Language Models](#w9)
| 10 | Tuesday, June 3 | [Final Project Discussion](#w10)

{{< pagebreak >}}

```{=typst}
#set align(left)
```

# Learning Objectives

- Understand how evidence drawn from statistical research methods can be used to inform decision-making in academia, government, and industry

- Acquire new language to engage in conversations about evidence-informed decision-making in a broad set of domains

- Practice discussing and writing about the application of new methods in quantitative and computational social science


# Requirements

POLI_SCI 210 or POLI_SCI 312 or equivalent experience with research design or data analysis.

# Required Reading

There is **no required textbook** for this course. Instead, readings for each are linked in the schedule below. All readings are available online for free or through university library subscription. 

**Readings are listed by intended reading order**

Readings for each week are divided by **theory** and **applications** of the methods, techniques, approaches, or issues we will discuss that week. In some weeks, we will discuss the theory first and applications second. In weeks in which the technical details are more dense, we will discuss applications first and theory second.

# Evaluation

Your final grade in this course will depend on the following: 

- Participation

- Discussion memos (due Mondays 9 AM)

- Final project: Pre-registration plan OR data exploration paper (due June 11, 11:59 PM)


## Participation

This course does not require attendance, but active engagement is a key component of a successful research seminar. Generally, that means attending class meetings regularly, doing the reading, asking questions, and working to foster a productive learning environment.

Beyond general guidelines, this course also has two specific avenues for participation.

1. **Leading class notes.** We will use collaboration tools to share our notes about the course material ahead of class meetings. Usually, one of us will serve as a discussion lead (either for a specific reading or for the whole week, depending on our collective preference). The lead will write a summary of their assigned piece(s) and propose talking points.

2. **Commenting on class notes.** On the weeks/readings that you are not leading the note-taking, you will contribute to the notes by including annotations with comments, questions, and additional talking points.

We will discuss additional details and expectations around participation during our first meeting. The general idea is to facilitate covering technical material in sufficient breadth and depth by combining division of labor with accountability.

Your participation inside and outside the classroom will be marked as satisfactory or unsatisfactory by the end of the quarter. If your participation leans toward an unsatisfactory mark, I will notify you by the end of Week 6 and give you feedback on how to improve.

## Discussion memos

On weeks of your choosing, you will write a document summarizing the key takeaways from our class meeting discussion of the material. The goal of this assignment is to facilitate more extensive reflection and expression than what is usually afforded by the conventional class structure.

Discussion memos should be around 1,000-1,500 words. As a general template, the document should answer (1) What topics did we discuss and how are they important? (2) What were the main issues we discussed and why are they interesting/important/consequential? (3) To which areas of interesting is our discussion relevant? Give 2-3 examples.

Discussion memos are due on Mondays at 9 AM **the week after** we discuss a topic and must be submitted on Canvas. Discussions memos will be marked as satisfactory or unsatisfactory. You may submit late discussion memos or resubmit those marked as unsatisfactory with instructor approval.

## Final project

As a final project, you will complete one of two assignments. In either case, your final project should be around 4,000 words and must be submitted on Canvas by June 11, 11:59 PM.

### Pre-registration plan

<!-- OSF prereg template -->
<!-- https://docs.google.com/document/d/1DaNmJEtBy04bq1l5OxS4JAscdZEkUGATURWwnBKLYxk/edit?tab=t.0 -->

[CONTINUE HERE]

### Data exploration paper




# Grading

This course uses a labor-based grading agreement, commonly known as contract grading. In this course, instead of being given a final grade based on how “good” your submitted assignments are, your final grade will be based on the amount of work you put into the course. The goal is to decouple grades from performance and emphasize learning and effort.

You will get [contract grading baseline]




# Northwestern University Syllabus Standards

This course follows the [Northwestern University Syllabus Standards](https://www.registrar.northwestern.edu/registration-graduation/northwestern-university-syllabus-standards.html). Students are responsible for familiarizing themselves with this information.


{{< pagebreak >}}

# Schedule

<!-- Save this because it also applies to ps210 -->
## Week 1 (Thursday, April 3): Preliminaries {#w1}

### Watch before meeting

- Gravert, Christina. ["Why we need evidence-based decisions in every business."](https://youtu.be/wKJPzHCLkTU?si=24bpF72tVlKgMz0x) TEDxManchester (15 minutes)

- Goldberg, Amir. ["Class Takeaways -- People Analytics."](https://youtu.be/mrT9NdLtKVk?si=-VTYMABfxXr18yWw) Stanford Graduate School of Business (5 minutes)



## Week 2 (April 8/10): The Evidence-Informed Movement {#w2}

<!-- Codex is not April 8 but I should be able to make it -->

### Theory

- Bluhm, Robyn and Kristin Borgerson. 2011. ["Evidence-Based Medicine."](https://doi.org/10.1016/B978-0-444-51787-6.50008-8) In *Philoshophy of Medicine*, pp. 203-238

- Bowers, Jake and Paul Testa. 2019. ["Better Government, Better Science: The Promise of and Challenges Facing the Evidence-Informed Policy Movement."](https://doi.org/10.1146/annurev-polisci-050517-124041) *Annual Review of Political Science* 22: 521-542

- Samii, Cyrus. 2023. ["Methodologies for 'Political Science as Problem Solving.'"](http://bit.ly/3FblFmc) Forthcoming in *Oxford Handbook of Methodological Pluralism*

### Applications

- Grant, Adam. 2019. ["The Surprising Value of Obvious Insights."](http://turing.library.northwestern.edu/login?url=https://www.proquest.com/scholarly-journals/surprising-value-obvious-insights/docview/2207931254/se-2?accountid=12861) *MIT Sloan Management Review* 60 (3): 8-10

- Congdon, William J. and Maya Shankar. 2015. ["The White House Social & Behavioral Sciences Team: Lessons learned from year one."](https://doi.org/10.1177/237946151500100209) *Behavioral Science & Policy* 1 (2): 77-86

- Kleibrin, Alexander and Edurne Magro. 2018. ["The making of responsive innovation policies: varieties of evidence and their contestation in the Basque Country."](https://doi.org/10.1057/s41599-018-0136-2) *Palgrave Communications* 4: 74

- Walker, Carl, Ewen Speed, and Danny Taggart. 2018. ["Turning psychology into policy: a case of square pegs and round holes?"](https://doi.org/10.1057/s41599-018-0159-8). *Palgrave Communications* 4: 108


## Week 3 (April 15/17): Randomized Controlled Trials {#w3}

### Theory

- Gertler, Paul J. et al. 2016. [*Impact Evaluation in Practice.*](https://openknowledge.worldbank.org/server/api/core/bitstreams/4659ef23-61ff-5df7-9b4e-89fda12b074d/content) Washington, DC: Inter-American Development Bank and World Bank. Chapters 3-4

- Rosenbaum, Paul. 2010. [*Design of Observational Studies.*](https://link.springer.com/book/10.1007/978-1-4419-1213-8) Springer. Chapter 2

### Applications

- Wilson, Kevin H. et al. 2024. ["A randomized controlled trial evaluating the effects of nurse-led triage of 911 calls."](https://doi.org/10.1038/s41562-024-01889-6) *Nature Human Behaviour* 8: 1276-1284

- Banerjee, Abhijit, Esther Duflo, and Garima Sharma. 2021. ["Long-Term Effects of the Targeting the Ultra Poor Program."](https://www.aeaweb.org/articles?id=10.1257/aeri.20200667) *American Economic Review: Insights* 3 (4): 471-486

- Kim, Jae Yeon, et al. 2025. "Administrative Checkpoints, Burdens, and Human-centered Design: Increasing Interview Access to Raise SNAP Participation." *Journal of Policy Analysis and Management* [URL coming soon]


## Week 4 (April 22/24): Learning from Experiments {#w4}

### Theory

- Deaton, Angus and Nancy Cartwright. 2018. ["Understanding and misunderstanding randomized controlled trials."](https://doi.org/10.1016/j.socscimed.2017.12.005) *Social Science & Medicine* 210: 2-21

- Giacomini, Mita. 2009. ["Theory-Based Medicine and the Role of Evidence: Why the Emperor Needs New Clothes, Again."](https://doi.org/10.1353/pbm.0.0088) *Perspectives in Biology and Medicine* 52 (2): 234-251

- Dubova, Marina, Arseny Moskvichev, and Kevin Zollman. 2023. ["Against theory-motivated experimentation in science."](https://doi.org/10.31222/osf.io/ysv2u) Working paper

### Applications

- Egami, Naoki, and Erin Hartman. 2023. ["Elements of External Validity: Framework, Design, and Analysis."](https://doi.org/10.1017/S0003055422000880) *American Political Science Review* 117 (3): 1070-1088 (skim mathematical details)

- Banerjee, Abhijit, et al. 2017. ["From Proof of Concept to Scalable Policies: Challenges and Solutions, with an Application."](https://www.aeaweb.org/articles?id=10.1257/jep.31.4.73) *Journal of Economic Perspectives* 31 (4): 73-102

- Corduneanu-Huci, Cristina, Michael T. Dorsch, and Paul Maarek. 2021. ["The politics of experimentation: Political competition and randomized controlled trials."](https://doi.org/10.1016/j.jce.2020.09.002) *Journal of Comparative Economics* 49 (1): 1-21

## Week 5 (April 29/May 1): Advanced Experimental Designs {#w5}

### Applications

- Blair, Graeme, et al. 2021. ["Community policing does not build citizen trust in police or reduce crime in the Global South."](https://doi.org/10.1126/science.abd3446) *Science* 374 (6571): eabd3446

- Slough, Tara, et al. 2021. ["Adoption of community monitoring improves common pool resource management across contexts."](https://doi.org/10.1073/pnas.2015367118) *Proceedings of the National Academi of Sciences* 118 (29): e2015367118

- Pennycook, Gordon, et al. 2021. ["Shifting attention to accuracy can reduce misinformation online."](https://doi.org/10.1038/s41586-021-03344-2) *Nature* 592: 590-595 (including the methods section)

- Lindon, Michael, et al. 2024. ["Sequential A/B Testing Keeps the World Streaming Netflix Part 1: Continuous Data."](https://netflixtechblog.com/sequential-a-b-testing-keeps-the-world-streaming-netflix-part-1-continuous-data-cba6c7ed49df) Netflix TechBlog

- Lindon, Michael, et al. 2024. ["Sequential A/B Testing Keeps the World Streaming Netflix Part 2: Counting Processes."](https://netflixtechblog.com/sequential-testing-keeps-the-world-streaming-netflix-part-2-counting-processes-da6805341642) Netflix TechBlog


### Guest lecture on adaptive experimentation ([Molly Offer-Westort](https://mollyow.github.io), University of Chicago)

- Offer-Westort, Molly and Leah R. Rosenzweig. 2025. ["Conversations with a concern-addressing chatbot increase COVID-19 vaccination intenations among social media users in Kenya and Nigeria."](https://doi.org/10.1086/735504) *Journal of Politics*

- Offer-Westort, Molly, Alexander Coppock, and Donald P. Green. 2021. ["Adaptive Experimental Design: Prospects and Applications in Political Science."](https://doi.org/10.1111/ajps.12597) *American Journal of Political Science* 65 (4): 826-844

- Offer-Westort, Molly, Vitor Hadad, and Susan Athey. ["Adaptive experimentation tutorial."](https://mollyow.shinyapps.io/adaptive/)

## Week 6 (May 6/8): Data Science to Help {#w6}

### Theory

- Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. 2021. ["Machine Learning for Social Science: An Agnostic Approach."](https://doi.org/10.1146/annurev-polisci-053119-015921) *Annual Review of Political Science* 24: 395-419

- Agrawal, Ajay, Joshua Gans, and Avi Goldfarb. 2018. [*Prediction Machines: The Simple Economics of Artificial Intelligence.*](https://github.com/Chandra0505/Data-Science-Resources/blob/master/machine-learning/Prediction%20Machines-The%20Simple%20Economics%20of%20Artificial%20Intelligence%20by%20Ajay%20Agrawal.pdf) Harvard Business Review Press. Chapters 1-11 (easy to read) 



### Applications

- Neal, Jean et al. 2016. ["Combining stallite imagery and machine learning to predict poverty."](https://doi.org/10.1126/science.aaf7894) *Science* 353 (6301): 790-794

- Bansak, Kirk et al. 2018. ["Improving refugee integration through data-drivel algorithmic assignment."](https://doi.org/10.1126/science.aao4408) *Science* 359 (6373): 325-329

- Hangartner, Dominik, Daniel Kopp, and Michael Siegenthaler. 2021. ["Monitoring hiring discrimination through online recruitment platforms."](https://doi.org/10.1038/s41586-020-03136-0) *Nature* 589: 572-576

- Ash, Elliott, Sergio Galletta, and Tommaso Giommoni. 2025. ["A Machine Learning Approach to Analyze and Support Anti-Corruption Policy."](https://dx.doi.org/10.2139/ssrn.3589545) *American Economic Journal: Economic Policy*


## Week 7 (May 13/15): Data Science to Harm {#w7}

### Applications

- Casey, Petec C., Kevin H. Wilson, and David Yokum. 2018. ["A Cautionary Tail: A Framework and Case Study for Testing Predictive Model Validity."](https://doi.org/10.48550/arXiv.1807.03860)

- Dressel, Julia and Hany Farid. 2018. ["The accuracy, fairness, and limits of predicting recidivism."](https://doi.org/10.1126/sciadv.aao5580) *Science Advances* 4 (1): eaao5580

- Angrave, David, et al. 2016. ["HR and analytics: Why HR is set to fail the big data challenge."](https://doi.org/10.1111/1748-8583.12090) *Human Resource Management Journal* 26 (1): 1-11

- Dellaert, Benedict G.C., Tom Baker, and Eric J. Johnson. 2024. ["Regulating robo-advice for consumers' financial decisions: The interplay between algortihm quality & digital choice architecture."](https://doi.org/10.1177/23794607241296686) *Behavioral Science & Policy*




### Theory

- Kleinberg, Jon, et al. 2018. ["Discrimination in the Age of Algorithms."](https://doi.org/10.1093/jla/laz001) *Journal of Legal Analysis* 10: 113-174

- Suresh, Harini and John Guttag. 2021. ["A Framework for Understanding Sources of Harm throughout the Machine Learning Life Cycle."](https://doi.org/10.1145/3465416.3483305) *EAAMO '21: Proceedings of the 1st ACM Conference on Equity and Access in Algorithms, Mechanisms, and Optimization* 

- Lopez, Paola. 2021. ["Bias does not equal bias: a socio-technical typology of bias in data-based algorithmic systems."](https://doi.org/10.14763/2021.4.1598) *Internet Policy Review* 10 (4)

- Imai, Kosuke and Zhichao Jiang. 2023. ["Principal Fairness for Human and Algorithmic Decision-Making."](https://doi.org/10.1214/22-STS872) *Statistical Science* 38 (2): 317-328


## Week 8 (May 20/22): AI and Experiments {#w8}

### Applications

- Dietrich, Bryce J. and Melissa L. Sands. 2023. ["Seeing racial avoidance on New York City Streets."](https://doi.org/10.1038/s41562-023-01589-7) *Nature Human Behaviour* 7: 1275-1281

- Camp, Nicholas P. et al. 2024. ["Leveraging body-worn camera footage to assess the effects of training on officer communication during traffic stops."](https://doi.org/10.1093/pnasnexus/pgae359) *PNAS Nexus* 3 (9): pgae359

- Imai, Kosuke et al. 2023. ["Experimental evaluation of algorithm-assisted human decision-making: Application to pretrial public safety assessment."](https://doi.org/10.1093/jrsssa/qnad010) *Journal of the Royal Statistical Society Series A: Statistics in Society* 186 (2): 167-189

### Theory

- Athey, Susan and Guido W. Imbens. 2019. ["Machine Learning Methods That Economists Should Know About."](https://doi.org/10.1146/annurev-economics-080217-053433) *Annual Review of Economics* 11: 685-725

- Brand, Jennie E., Xiang Zhou, and Yu Xie. 2023. ["Recent Developments in Causal Inference and Machine Learning."](https://doi.org/10.1146/annurev-soc-030420-015345) *Annual Revew of Sociology* 49: 81-110


## Week 9 (May 27/29): Large Language Models {#w9}

[Schedule TBD depending on guest speaker]

https://mbosley.github.io/papers/ai-prejudice-paper.pdf

https://elliottash.com/wp-content/uploads/2025/03/Ash-Galletta-Opocher-BallotBot-AI-Strengthen-Democracy.pdf

https://doi.org/10.48550/arXiv.2412.15060

https://arxiv.org/abs/2410.19202

https://doi.org/10.1017/pan.2023.2

https://doi.org/10.1177/23794607241311793

https://doi.org/10.1080/00323187.2024.2335471

## Week 10 (Tuesday, June 3): Final Project Discussion {#w10}

WCAS Reading Week Starts on June 4